import turtle
t = turtle.Turtle()
t.pensize(2)
turtle.Screen().bgcolor("black")

for i in range(6):
    t.pencolor("red")
    t.circle(100)
    t.left(10)
    t.pencolor("white")
    t.circle(100)
    t.left(10)
    t.pencolor("yellow")
    t.circle(100)
    t.left(10)
    t.pencolor("green")
    t.circle(100)
    t.left(10)
    t.pencolor("pink")
    t.circle(100)
    t.left(10)
    t.pencolor("blue")
    t.circle(100)
    t.left(10)
turtle.done()
